void debug_int_assign(int *var, char *var_name, int value);
void debug_float_assign(float *var, char *var_name, float value);
void debug_char_assign(char *var, char *var_name, char value);
void debug_call_func_no_args(int (*func)(), char *func_name);
void debug_str_assign(char **var, char *var_name, char *value);
FILE *debug_fopen(const char *name, char *mode, FILE *var, char *var_name);
void make_arr(char ****machine_prog, int width, int height, int *err);
void check_prog_size(char *command, int *width, int *height, int *err);
void parse_commands(FILE *prog_file, char ****machine_prog, int width, int height);
void print_prog(char ***machine_prog, int width, int height);
void free_all(FILE **prog_file, FILE **word_file, char **word, char **command, char ****machine_prog, int width, int height, char **tape_ptr, char **alphabet);
int get_current_command_index(char symbol, int width, char *alphabet);
void get_current_symbol(char **word, int current_word_index, char *symbol);
void write_new_symbol(char ***word, int current_word_index, char *current_prog);
void move_head(char *current_prog, int *current_word_index);
void change_status(int *status, char *current_prog, int *prog_end);
void execute_prog(char ***prog, int width, char **word, char *alphabet, char *tape_ptr);
int make_tape_for_word(char *word, int word_len, char **tape_ptr, char **tape_center_ptr);
char *get_alphabet(FILE *prog_file);
